server:

  port: 10001
spring:
  application:
    name: QBsource-web-Server
  datasource:
    url: jdbc:mysql://leng45.eicp.net:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: noroot
    driver_class_namel: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max_active: 20
    initial_size: 1
    min_idle: 3
    max_wait: 60000
    time_between_eviction_runs_millis: 60000
    min_evictable_idle_time_millis: 300000
    test_while_idle: true
    test_on_borrow: false
    test_on_return: false
    poolPreparedStatements: true

#ftp配置
ftp:
  url: localhost
  port: 14147
  userName: test
  passWord: 123456

#文件参数
attachment:
  #txt
  txtFile:
    dirRoot: /情报素材/
    type: txt
  #doc
  docFile:
    dirRoot: /AOService/
    type: doc
    
debug: true