package deepthinking.domain;

import java.util.Date;

public class TbYwScsjFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.SCID
     *
     * @mbg.generated
     */
    private String scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.KM
     *
     * @mbg.generated
     */
    private String km;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.BM
     *
     * @mbg.generated
     */
    private String bm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.YBS
     *
     * @mbg.generated
     */
    private String ybs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.ZT
     *
     * @mbg.generated
     */
    private String zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.RKSJ
     *
     * @mbg.generated
     */
    private Date rksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.SCBT
     *
     * @mbg.generated
     */
    private String scbt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.SCDX
     *
     * @mbg.generated
     */
    private Integer scdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.SCLJ
     *
     * @mbg.generated
     */
    private String sclj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.SCGS
     *
     * @mbg.generated
     */
    private String scgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.SCLB
     *
     * @mbg.generated
     */
    private String sclb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.LRRY
     *
     * @mbg.generated
     */
    private String lrry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.LRSJ
     *
     * @mbg.generated
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.BWXS
     *
     * @mbg.generated
     */
    private String bwxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.MMDJ
     *
     * @mbg.generated
     */
    private String mmdj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.FWSJ
     *
     * @mbg.generated
     */
    private Date fwsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.CSSJ
     *
     * @mbg.generated
     */
    private Date cssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.FWBH
     *
     * @mbg.generated
     */
    private String fwbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.QF
     *
     * @mbg.generated
     */
    private String qf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.BZ
     *
     * @mbg.generated
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.ZTC
     *
     * @mbg.generated
     */
    private String ztc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.TJM
     *
     * @mbg.generated
     */
    private String tjm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.LWDW
     *
     * @mbg.generated
     */
    private String lwdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_YW_SCSJ_FILE.NR
     *
     * @mbg.generated
     */
    private byte[] nr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.SCID
     *
     * @return the value of TB_YW_SCSJ_FILE.SCID
     *
     * @mbg.generated
     */
    public String getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.SCID
     *
     * @param scid the value for TB_YW_SCSJ_FILE.SCID
     *
     * @mbg.generated
     */
    public void setScid(String scid) {
        this.scid = scid == null ? null : scid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.KM
     *
     * @return the value of TB_YW_SCSJ_FILE.KM
     *
     * @mbg.generated
     */
    public String getKm() {
        return km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.KM
     *
     * @param km the value for TB_YW_SCSJ_FILE.KM
     *
     * @mbg.generated
     */
    public void setKm(String km) {
        this.km = km == null ? null : km.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.BM
     *
     * @return the value of TB_YW_SCSJ_FILE.BM
     *
     * @mbg.generated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.BM
     *
     * @param bm the value for TB_YW_SCSJ_FILE.BM
     *
     * @mbg.generated
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.YBS
     *
     * @return the value of TB_YW_SCSJ_FILE.YBS
     *
     * @mbg.generated
     */
    public String getYbs() {
        return ybs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.YBS
     *
     * @param ybs the value for TB_YW_SCSJ_FILE.YBS
     *
     * @mbg.generated
     */
    public void setYbs(String ybs) {
        this.ybs = ybs == null ? null : ybs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.ZT
     *
     * @return the value of TB_YW_SCSJ_FILE.ZT
     *
     * @mbg.generated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.ZT
     *
     * @param zt the value for TB_YW_SCSJ_FILE.ZT
     *
     * @mbg.generated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.RKSJ
     *
     * @return the value of TB_YW_SCSJ_FILE.RKSJ
     *
     * @mbg.generated
     */
    public Date getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.RKSJ
     *
     * @param rksj the value for TB_YW_SCSJ_FILE.RKSJ
     *
     * @mbg.generated
     */
    public void setRksj(Date rksj) {
        this.rksj = rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.SCBT
     *
     * @return the value of TB_YW_SCSJ_FILE.SCBT
     *
     * @mbg.generated
     */
    public String getScbt() {
        return scbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.SCBT
     *
     * @param scbt the value for TB_YW_SCSJ_FILE.SCBT
     *
     * @mbg.generated
     */
    public void setScbt(String scbt) {
        this.scbt = scbt == null ? null : scbt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.SCDX
     *
     * @return the value of TB_YW_SCSJ_FILE.SCDX
     *
     * @mbg.generated
     */
    public Integer getScdx() {
        return scdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.SCDX
     *
     * @param scdx the value for TB_YW_SCSJ_FILE.SCDX
     *
     * @mbg.generated
     */
    public void setScdx(Integer scdx) {
        this.scdx = scdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.SCLJ
     *
     * @return the value of TB_YW_SCSJ_FILE.SCLJ
     *
     * @mbg.generated
     */
    public String getSclj() {
        return sclj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.SCLJ
     *
     * @param sclj the value for TB_YW_SCSJ_FILE.SCLJ
     *
     * @mbg.generated
     */
    public void setSclj(String sclj) {
        this.sclj = sclj == null ? null : sclj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.SCGS
     *
     * @return the value of TB_YW_SCSJ_FILE.SCGS
     *
     * @mbg.generated
     */
    public String getScgs() {
        return scgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.SCGS
     *
     * @param scgs the value for TB_YW_SCSJ_FILE.SCGS
     *
     * @mbg.generated
     */
    public void setScgs(String scgs) {
        this.scgs = scgs == null ? null : scgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.SCLB
     *
     * @return the value of TB_YW_SCSJ_FILE.SCLB
     *
     * @mbg.generated
     */
    public String getSclb() {
        return sclb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.SCLB
     *
     * @param sclb the value for TB_YW_SCSJ_FILE.SCLB
     *
     * @mbg.generated
     */
    public void setSclb(String sclb) {
        this.sclb = sclb == null ? null : sclb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.LRRY
     *
     * @return the value of TB_YW_SCSJ_FILE.LRRY
     *
     * @mbg.generated
     */
    public String getLrry() {
        return lrry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.LRRY
     *
     * @param lrry the value for TB_YW_SCSJ_FILE.LRRY
     *
     * @mbg.generated
     */
    public void setLrry(String lrry) {
        this.lrry = lrry == null ? null : lrry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.LRSJ
     *
     * @return the value of TB_YW_SCSJ_FILE.LRSJ
     *
     * @mbg.generated
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.LRSJ
     *
     * @param lrsj the value for TB_YW_SCSJ_FILE.LRSJ
     *
     * @mbg.generated
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.BWXS
     *
     * @return the value of TB_YW_SCSJ_FILE.BWXS
     *
     * @mbg.generated
     */
    public String getBwxs() {
        return bwxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.BWXS
     *
     * @param bwxs the value for TB_YW_SCSJ_FILE.BWXS
     *
     * @mbg.generated
     */
    public void setBwxs(String bwxs) {
        this.bwxs = bwxs == null ? null : bwxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.MMDJ
     *
     * @return the value of TB_YW_SCSJ_FILE.MMDJ
     *
     * @mbg.generated
     */
    public String getMmdj() {
        return mmdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.MMDJ
     *
     * @param mmdj the value for TB_YW_SCSJ_FILE.MMDJ
     *
     * @mbg.generated
     */
    public void setMmdj(String mmdj) {
        this.mmdj = mmdj == null ? null : mmdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.FWSJ
     *
     * @return the value of TB_YW_SCSJ_FILE.FWSJ
     *
     * @mbg.generated
     */
    public Date getFwsj() {
        return fwsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.FWSJ
     *
     * @param fwsj the value for TB_YW_SCSJ_FILE.FWSJ
     *
     * @mbg.generated
     */
    public void setFwsj(Date fwsj) {
        this.fwsj = fwsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.CSSJ
     *
     * @return the value of TB_YW_SCSJ_FILE.CSSJ
     *
     * @mbg.generated
     */
    public Date getCssj() {
        return cssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.CSSJ
     *
     * @param cssj the value for TB_YW_SCSJ_FILE.CSSJ
     *
     * @mbg.generated
     */
    public void setCssj(Date cssj) {
        this.cssj = cssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.FWBH
     *
     * @return the value of TB_YW_SCSJ_FILE.FWBH
     *
     * @mbg.generated
     */
    public String getFwbh() {
        return fwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.FWBH
     *
     * @param fwbh the value for TB_YW_SCSJ_FILE.FWBH
     *
     * @mbg.generated
     */
    public void setFwbh(String fwbh) {
        this.fwbh = fwbh == null ? null : fwbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.QF
     *
     * @return the value of TB_YW_SCSJ_FILE.QF
     *
     * @mbg.generated
     */
    public String getQf() {
        return qf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.QF
     *
     * @param qf the value for TB_YW_SCSJ_FILE.QF
     *
     * @mbg.generated
     */
    public void setQf(String qf) {
        this.qf = qf == null ? null : qf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.BZ
     *
     * @return the value of TB_YW_SCSJ_FILE.BZ
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.BZ
     *
     * @param bz the value for TB_YW_SCSJ_FILE.BZ
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.ZTC
     *
     * @return the value of TB_YW_SCSJ_FILE.ZTC
     *
     * @mbg.generated
     */
    public String getZtc() {
        return ztc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.ZTC
     *
     * @param ztc the value for TB_YW_SCSJ_FILE.ZTC
     *
     * @mbg.generated
     */
    public void setZtc(String ztc) {
        this.ztc = ztc == null ? null : ztc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.TJM
     *
     * @return the value of TB_YW_SCSJ_FILE.TJM
     *
     * @mbg.generated
     */
    public String getTjm() {
        return tjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.TJM
     *
     * @param tjm the value for TB_YW_SCSJ_FILE.TJM
     *
     * @mbg.generated
     */
    public void setTjm(String tjm) {
        this.tjm = tjm == null ? null : tjm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.LWDW
     *
     * @return the value of TB_YW_SCSJ_FILE.LWDW
     *
     * @mbg.generated
     */
    public String getLwdw() {
        return lwdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.LWDW
     *
     * @param lwdw the value for TB_YW_SCSJ_FILE.LWDW
     *
     * @mbg.generated
     */
    public void setLwdw(String lwdw) {
        this.lwdw = lwdw == null ? null : lwdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_YW_SCSJ_FILE.NR
     *
     * @return the value of TB_YW_SCSJ_FILE.NR
     *
     * @mbg.generated
     */
    public byte[] getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_YW_SCSJ_FILE.NR
     *
     * @param nr the value for TB_YW_SCSJ_FILE.NR
     *
     * @mbg.generated
     */
    public void setNr(byte[] nr) {
        this.nr = nr;
    }
}