package deepthinking.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbYwScsjFileCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public TbYwScsjFileCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andScidIsNull() {
            addCriterion("SCID is null");
            return (Criteria) this;
        }

        public Criteria andScidIsNotNull() {
            addCriterion("SCID is not null");
            return (Criteria) this;
        }

        public Criteria andScidEqualTo(String value) {
            addCriterion("SCID =", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotEqualTo(String value) {
            addCriterion("SCID <>", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidGreaterThan(String value) {
            addCriterion("SCID >", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidGreaterThanOrEqualTo(String value) {
            addCriterion("SCID >=", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLessThan(String value) {
            addCriterion("SCID <", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLessThanOrEqualTo(String value) {
            addCriterion("SCID <=", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLike(String value) {
            addCriterion("SCID like", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotLike(String value) {
            addCriterion("SCID not like", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidIn(List<String> values) {
            addCriterion("SCID in", values, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotIn(List<String> values) {
            addCriterion("SCID not in", values, "scid");
            return (Criteria) this;
        }

        public Criteria andScidBetween(String value1, String value2) {
            addCriterion("SCID between", value1, value2, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotBetween(String value1, String value2) {
            addCriterion("SCID not between", value1, value2, "scid");
            return (Criteria) this;
        }

        public Criteria andKmIsNull() {
            addCriterion("KM is null");
            return (Criteria) this;
        }

        public Criteria andKmIsNotNull() {
            addCriterion("KM is not null");
            return (Criteria) this;
        }

        public Criteria andKmEqualTo(String value) {
            addCriterion("KM =", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmNotEqualTo(String value) {
            addCriterion("KM <>", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmGreaterThan(String value) {
            addCriterion("KM >", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmGreaterThanOrEqualTo(String value) {
            addCriterion("KM >=", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmLessThan(String value) {
            addCriterion("KM <", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmLessThanOrEqualTo(String value) {
            addCriterion("KM <=", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmLike(String value) {
            addCriterion("KM like", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmNotLike(String value) {
            addCriterion("KM not like", value, "km");
            return (Criteria) this;
        }

        public Criteria andKmIn(List<String> values) {
            addCriterion("KM in", values, "km");
            return (Criteria) this;
        }

        public Criteria andKmNotIn(List<String> values) {
            addCriterion("KM not in", values, "km");
            return (Criteria) this;
        }

        public Criteria andKmBetween(String value1, String value2) {
            addCriterion("KM between", value1, value2, "km");
            return (Criteria) this;
        }

        public Criteria andKmNotBetween(String value1, String value2) {
            addCriterion("KM not between", value1, value2, "km");
            return (Criteria) this;
        }

        public Criteria andBmIsNull() {
            addCriterion("BM is null");
            return (Criteria) this;
        }

        public Criteria andBmIsNotNull() {
            addCriterion("BM is not null");
            return (Criteria) this;
        }

        public Criteria andBmEqualTo(String value) {
            addCriterion("BM =", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmNotEqualTo(String value) {
            addCriterion("BM <>", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmGreaterThan(String value) {
            addCriterion("BM >", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmGreaterThanOrEqualTo(String value) {
            addCriterion("BM >=", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmLessThan(String value) {
            addCriterion("BM <", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmLessThanOrEqualTo(String value) {
            addCriterion("BM <=", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmLike(String value) {
            addCriterion("BM like", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmNotLike(String value) {
            addCriterion("BM not like", value, "bm");
            return (Criteria) this;
        }

        public Criteria andBmIn(List<String> values) {
            addCriterion("BM in", values, "bm");
            return (Criteria) this;
        }

        public Criteria andBmNotIn(List<String> values) {
            addCriterion("BM not in", values, "bm");
            return (Criteria) this;
        }

        public Criteria andBmBetween(String value1, String value2) {
            addCriterion("BM between", value1, value2, "bm");
            return (Criteria) this;
        }

        public Criteria andBmNotBetween(String value1, String value2) {
            addCriterion("BM not between", value1, value2, "bm");
            return (Criteria) this;
        }

        public Criteria andYbsIsNull() {
            addCriterion("YBS is null");
            return (Criteria) this;
        }

        public Criteria andYbsIsNotNull() {
            addCriterion("YBS is not null");
            return (Criteria) this;
        }

        public Criteria andYbsEqualTo(String value) {
            addCriterion("YBS =", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsNotEqualTo(String value) {
            addCriterion("YBS <>", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsGreaterThan(String value) {
            addCriterion("YBS >", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsGreaterThanOrEqualTo(String value) {
            addCriterion("YBS >=", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsLessThan(String value) {
            addCriterion("YBS <", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsLessThanOrEqualTo(String value) {
            addCriterion("YBS <=", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsLike(String value) {
            addCriterion("YBS like", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsNotLike(String value) {
            addCriterion("YBS not like", value, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsIn(List<String> values) {
            addCriterion("YBS in", values, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsNotIn(List<String> values) {
            addCriterion("YBS not in", values, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsBetween(String value1, String value2) {
            addCriterion("YBS between", value1, value2, "ybs");
            return (Criteria) this;
        }

        public Criteria andYbsNotBetween(String value1, String value2) {
            addCriterion("YBS not between", value1, value2, "ybs");
            return (Criteria) this;
        }

        public Criteria andZtIsNull() {
            addCriterion("ZT is null");
            return (Criteria) this;
        }

        public Criteria andZtIsNotNull() {
            addCriterion("ZT is not null");
            return (Criteria) this;
        }

        public Criteria andZtEqualTo(String value) {
            addCriterion("ZT =", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotEqualTo(String value) {
            addCriterion("ZT <>", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtGreaterThan(String value) {
            addCriterion("ZT >", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtGreaterThanOrEqualTo(String value) {
            addCriterion("ZT >=", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLessThan(String value) {
            addCriterion("ZT <", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLessThanOrEqualTo(String value) {
            addCriterion("ZT <=", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLike(String value) {
            addCriterion("ZT like", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotLike(String value) {
            addCriterion("ZT not like", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtIn(List<String> values) {
            addCriterion("ZT in", values, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotIn(List<String> values) {
            addCriterion("ZT not in", values, "zt");
            return (Criteria) this;
        }

        public Criteria andZtBetween(String value1, String value2) {
            addCriterion("ZT between", value1, value2, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotBetween(String value1, String value2) {
            addCriterion("ZT not between", value1, value2, "zt");
            return (Criteria) this;
        }

        public Criteria andRksjIsNull() {
            addCriterion("RKSJ is null");
            return (Criteria) this;
        }

        public Criteria andRksjIsNotNull() {
            addCriterion("RKSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRksjEqualTo(Date value) {
            addCriterionForJDBCDate("RKSJ =", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotEqualTo(Date value) {
            addCriterionForJDBCDate("RKSJ <>", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThan(Date value) {
            addCriterionForJDBCDate("RKSJ >", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RKSJ >=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThan(Date value) {
            addCriterionForJDBCDate("RKSJ <", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RKSJ <=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjIn(List<Date> values) {
            addCriterionForJDBCDate("RKSJ in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotIn(List<Date> values) {
            addCriterionForJDBCDate("RKSJ not in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RKSJ between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RKSJ not between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andScbtIsNull() {
            addCriterion("SCBT is null");
            return (Criteria) this;
        }

        public Criteria andScbtIsNotNull() {
            addCriterion("SCBT is not null");
            return (Criteria) this;
        }

        public Criteria andScbtEqualTo(String value) {
            addCriterion("SCBT =", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtNotEqualTo(String value) {
            addCriterion("SCBT <>", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtGreaterThan(String value) {
            addCriterion("SCBT >", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtGreaterThanOrEqualTo(String value) {
            addCriterion("SCBT >=", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtLessThan(String value) {
            addCriterion("SCBT <", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtLessThanOrEqualTo(String value) {
            addCriterion("SCBT <=", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtLike(String value) {
            addCriterion("SCBT like", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtNotLike(String value) {
            addCriterion("SCBT not like", value, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtIn(List<String> values) {
            addCriterion("SCBT in", values, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtNotIn(List<String> values) {
            addCriterion("SCBT not in", values, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtBetween(String value1, String value2) {
            addCriterion("SCBT between", value1, value2, "scbt");
            return (Criteria) this;
        }

        public Criteria andScbtNotBetween(String value1, String value2) {
            addCriterion("SCBT not between", value1, value2, "scbt");
            return (Criteria) this;
        }

        public Criteria andScdxIsNull() {
            addCriterion("SCDX is null");
            return (Criteria) this;
        }

        public Criteria andScdxIsNotNull() {
            addCriterion("SCDX is not null");
            return (Criteria) this;
        }

        public Criteria andScdxEqualTo(Integer value) {
            addCriterion("SCDX =", value, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxNotEqualTo(Integer value) {
            addCriterion("SCDX <>", value, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxGreaterThan(Integer value) {
            addCriterion("SCDX >", value, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("SCDX >=", value, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxLessThan(Integer value) {
            addCriterion("SCDX <", value, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxLessThanOrEqualTo(Integer value) {
            addCriterion("SCDX <=", value, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxIn(List<Integer> values) {
            addCriterion("SCDX in", values, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxNotIn(List<Integer> values) {
            addCriterion("SCDX not in", values, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxBetween(Integer value1, Integer value2) {
            addCriterion("SCDX between", value1, value2, "scdx");
            return (Criteria) this;
        }

        public Criteria andScdxNotBetween(Integer value1, Integer value2) {
            addCriterion("SCDX not between", value1, value2, "scdx");
            return (Criteria) this;
        }

        public Criteria andScljIsNull() {
            addCriterion("SCLJ is null");
            return (Criteria) this;
        }

        public Criteria andScljIsNotNull() {
            addCriterion("SCLJ is not null");
            return (Criteria) this;
        }

        public Criteria andScljEqualTo(String value) {
            addCriterion("SCLJ =", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljNotEqualTo(String value) {
            addCriterion("SCLJ <>", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljGreaterThan(String value) {
            addCriterion("SCLJ >", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljGreaterThanOrEqualTo(String value) {
            addCriterion("SCLJ >=", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljLessThan(String value) {
            addCriterion("SCLJ <", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljLessThanOrEqualTo(String value) {
            addCriterion("SCLJ <=", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljLike(String value) {
            addCriterion("SCLJ like", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljNotLike(String value) {
            addCriterion("SCLJ not like", value, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljIn(List<String> values) {
            addCriterion("SCLJ in", values, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljNotIn(List<String> values) {
            addCriterion("SCLJ not in", values, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljBetween(String value1, String value2) {
            addCriterion("SCLJ between", value1, value2, "sclj");
            return (Criteria) this;
        }

        public Criteria andScljNotBetween(String value1, String value2) {
            addCriterion("SCLJ not between", value1, value2, "sclj");
            return (Criteria) this;
        }

        public Criteria andScgsIsNull() {
            addCriterion("SCGS is null");
            return (Criteria) this;
        }

        public Criteria andScgsIsNotNull() {
            addCriterion("SCGS is not null");
            return (Criteria) this;
        }

        public Criteria andScgsEqualTo(String value) {
            addCriterion("SCGS =", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsNotEqualTo(String value) {
            addCriterion("SCGS <>", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsGreaterThan(String value) {
            addCriterion("SCGS >", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsGreaterThanOrEqualTo(String value) {
            addCriterion("SCGS >=", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsLessThan(String value) {
            addCriterion("SCGS <", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsLessThanOrEqualTo(String value) {
            addCriterion("SCGS <=", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsLike(String value) {
            addCriterion("SCGS like", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsNotLike(String value) {
            addCriterion("SCGS not like", value, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsIn(List<String> values) {
            addCriterion("SCGS in", values, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsNotIn(List<String> values) {
            addCriterion("SCGS not in", values, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsBetween(String value1, String value2) {
            addCriterion("SCGS between", value1, value2, "scgs");
            return (Criteria) this;
        }

        public Criteria andScgsNotBetween(String value1, String value2) {
            addCriterion("SCGS not between", value1, value2, "scgs");
            return (Criteria) this;
        }

        public Criteria andSclbIsNull() {
            addCriterion("SCLB is null");
            return (Criteria) this;
        }

        public Criteria andSclbIsNotNull() {
            addCriterion("SCLB is not null");
            return (Criteria) this;
        }

        public Criteria andSclbEqualTo(String value) {
            addCriterion("SCLB =", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbNotEqualTo(String value) {
            addCriterion("SCLB <>", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbGreaterThan(String value) {
            addCriterion("SCLB >", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbGreaterThanOrEqualTo(String value) {
            addCriterion("SCLB >=", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbLessThan(String value) {
            addCriterion("SCLB <", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbLessThanOrEqualTo(String value) {
            addCriterion("SCLB <=", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbLike(String value) {
            addCriterion("SCLB like", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbNotLike(String value) {
            addCriterion("SCLB not like", value, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbIn(List<String> values) {
            addCriterion("SCLB in", values, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbNotIn(List<String> values) {
            addCriterion("SCLB not in", values, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbBetween(String value1, String value2) {
            addCriterion("SCLB between", value1, value2, "sclb");
            return (Criteria) this;
        }

        public Criteria andSclbNotBetween(String value1, String value2) {
            addCriterion("SCLB not between", value1, value2, "sclb");
            return (Criteria) this;
        }

        public Criteria andLrryIsNull() {
            addCriterion("LRRY is null");
            return (Criteria) this;
        }

        public Criteria andLrryIsNotNull() {
            addCriterion("LRRY is not null");
            return (Criteria) this;
        }

        public Criteria andLrryEqualTo(String value) {
            addCriterion("LRRY =", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryNotEqualTo(String value) {
            addCriterion("LRRY <>", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryGreaterThan(String value) {
            addCriterion("LRRY >", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryGreaterThanOrEqualTo(String value) {
            addCriterion("LRRY >=", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryLessThan(String value) {
            addCriterion("LRRY <", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryLessThanOrEqualTo(String value) {
            addCriterion("LRRY <=", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryLike(String value) {
            addCriterion("LRRY like", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryNotLike(String value) {
            addCriterion("LRRY not like", value, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryIn(List<String> values) {
            addCriterion("LRRY in", values, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryNotIn(List<String> values) {
            addCriterion("LRRY not in", values, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryBetween(String value1, String value2) {
            addCriterion("LRRY between", value1, value2, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrryNotBetween(String value1, String value2) {
            addCriterion("LRRY not between", value1, value2, "lrry");
            return (Criteria) this;
        }

        public Criteria andLrsjIsNull() {
            addCriterion("LRSJ is null");
            return (Criteria) this;
        }

        public Criteria andLrsjIsNotNull() {
            addCriterion("LRSJ is not null");
            return (Criteria) this;
        }

        public Criteria andLrsjEqualTo(Date value) {
            addCriterionForJDBCDate("LRSJ =", value, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("LRSJ <>", value, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjGreaterThan(Date value) {
            addCriterionForJDBCDate("LRSJ >", value, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LRSJ >=", value, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjLessThan(Date value) {
            addCriterionForJDBCDate("LRSJ <", value, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LRSJ <=", value, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjIn(List<Date> values) {
            addCriterionForJDBCDate("LRSJ in", values, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("LRSJ not in", values, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LRSJ between", value1, value2, "lrsj");
            return (Criteria) this;
        }

        public Criteria andLrsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LRSJ not between", value1, value2, "lrsj");
            return (Criteria) this;
        }

        public Criteria andBwxsIsNull() {
            addCriterion("BWXS is null");
            return (Criteria) this;
        }

        public Criteria andBwxsIsNotNull() {
            addCriterion("BWXS is not null");
            return (Criteria) this;
        }

        public Criteria andBwxsEqualTo(String value) {
            addCriterion("BWXS =", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsNotEqualTo(String value) {
            addCriterion("BWXS <>", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsGreaterThan(String value) {
            addCriterion("BWXS >", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsGreaterThanOrEqualTo(String value) {
            addCriterion("BWXS >=", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsLessThan(String value) {
            addCriterion("BWXS <", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsLessThanOrEqualTo(String value) {
            addCriterion("BWXS <=", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsLike(String value) {
            addCriterion("BWXS like", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsNotLike(String value) {
            addCriterion("BWXS not like", value, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsIn(List<String> values) {
            addCriterion("BWXS in", values, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsNotIn(List<String> values) {
            addCriterion("BWXS not in", values, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsBetween(String value1, String value2) {
            addCriterion("BWXS between", value1, value2, "bwxs");
            return (Criteria) this;
        }

        public Criteria andBwxsNotBetween(String value1, String value2) {
            addCriterion("BWXS not between", value1, value2, "bwxs");
            return (Criteria) this;
        }

        public Criteria andMmdjIsNull() {
            addCriterion("MMDJ is null");
            return (Criteria) this;
        }

        public Criteria andMmdjIsNotNull() {
            addCriterion("MMDJ is not null");
            return (Criteria) this;
        }

        public Criteria andMmdjEqualTo(String value) {
            addCriterion("MMDJ =", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjNotEqualTo(String value) {
            addCriterion("MMDJ <>", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjGreaterThan(String value) {
            addCriterion("MMDJ >", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjGreaterThanOrEqualTo(String value) {
            addCriterion("MMDJ >=", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjLessThan(String value) {
            addCriterion("MMDJ <", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjLessThanOrEqualTo(String value) {
            addCriterion("MMDJ <=", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjLike(String value) {
            addCriterion("MMDJ like", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjNotLike(String value) {
            addCriterion("MMDJ not like", value, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjIn(List<String> values) {
            addCriterion("MMDJ in", values, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjNotIn(List<String> values) {
            addCriterion("MMDJ not in", values, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjBetween(String value1, String value2) {
            addCriterion("MMDJ between", value1, value2, "mmdj");
            return (Criteria) this;
        }

        public Criteria andMmdjNotBetween(String value1, String value2) {
            addCriterion("MMDJ not between", value1, value2, "mmdj");
            return (Criteria) this;
        }

        public Criteria andFwsjIsNull() {
            addCriterion("FWSJ is null");
            return (Criteria) this;
        }

        public Criteria andFwsjIsNotNull() {
            addCriterion("FWSJ is not null");
            return (Criteria) this;
        }

        public Criteria andFwsjEqualTo(Date value) {
            addCriterionForJDBCDate("FWSJ =", value, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("FWSJ <>", value, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjGreaterThan(Date value) {
            addCriterionForJDBCDate("FWSJ >", value, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FWSJ >=", value, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjLessThan(Date value) {
            addCriterionForJDBCDate("FWSJ <", value, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FWSJ <=", value, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjIn(List<Date> values) {
            addCriterionForJDBCDate("FWSJ in", values, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("FWSJ not in", values, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FWSJ between", value1, value2, "fwsj");
            return (Criteria) this;
        }

        public Criteria andFwsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FWSJ not between", value1, value2, "fwsj");
            return (Criteria) this;
        }

        public Criteria andCssjIsNull() {
            addCriterion("CSSJ is null");
            return (Criteria) this;
        }

        public Criteria andCssjIsNotNull() {
            addCriterion("CSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andCssjEqualTo(Date value) {
            addCriterionForJDBCDate("CSSJ =", value, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjNotEqualTo(Date value) {
            addCriterionForJDBCDate("CSSJ <>", value, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjGreaterThan(Date value) {
            addCriterionForJDBCDate("CSSJ >", value, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CSSJ >=", value, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjLessThan(Date value) {
            addCriterionForJDBCDate("CSSJ <", value, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CSSJ <=", value, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjIn(List<Date> values) {
            addCriterionForJDBCDate("CSSJ in", values, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjNotIn(List<Date> values) {
            addCriterionForJDBCDate("CSSJ not in", values, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CSSJ between", value1, value2, "cssj");
            return (Criteria) this;
        }

        public Criteria andCssjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CSSJ not between", value1, value2, "cssj");
            return (Criteria) this;
        }

        public Criteria andFwbhIsNull() {
            addCriterion("FWBH is null");
            return (Criteria) this;
        }

        public Criteria andFwbhIsNotNull() {
            addCriterion("FWBH is not null");
            return (Criteria) this;
        }

        public Criteria andFwbhEqualTo(String value) {
            addCriterion("FWBH =", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhNotEqualTo(String value) {
            addCriterion("FWBH <>", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhGreaterThan(String value) {
            addCriterion("FWBH >", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhGreaterThanOrEqualTo(String value) {
            addCriterion("FWBH >=", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhLessThan(String value) {
            addCriterion("FWBH <", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhLessThanOrEqualTo(String value) {
            addCriterion("FWBH <=", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhLike(String value) {
            addCriterion("FWBH like", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhNotLike(String value) {
            addCriterion("FWBH not like", value, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhIn(List<String> values) {
            addCriterion("FWBH in", values, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhNotIn(List<String> values) {
            addCriterion("FWBH not in", values, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhBetween(String value1, String value2) {
            addCriterion("FWBH between", value1, value2, "fwbh");
            return (Criteria) this;
        }

        public Criteria andFwbhNotBetween(String value1, String value2) {
            addCriterion("FWBH not between", value1, value2, "fwbh");
            return (Criteria) this;
        }

        public Criteria andQfIsNull() {
            addCriterion("QF is null");
            return (Criteria) this;
        }

        public Criteria andQfIsNotNull() {
            addCriterion("QF is not null");
            return (Criteria) this;
        }

        public Criteria andQfEqualTo(String value) {
            addCriterion("QF =", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfNotEqualTo(String value) {
            addCriterion("QF <>", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfGreaterThan(String value) {
            addCriterion("QF >", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfGreaterThanOrEqualTo(String value) {
            addCriterion("QF >=", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfLessThan(String value) {
            addCriterion("QF <", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfLessThanOrEqualTo(String value) {
            addCriterion("QF <=", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfLike(String value) {
            addCriterion("QF like", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfNotLike(String value) {
            addCriterion("QF not like", value, "qf");
            return (Criteria) this;
        }

        public Criteria andQfIn(List<String> values) {
            addCriterion("QF in", values, "qf");
            return (Criteria) this;
        }

        public Criteria andQfNotIn(List<String> values) {
            addCriterion("QF not in", values, "qf");
            return (Criteria) this;
        }

        public Criteria andQfBetween(String value1, String value2) {
            addCriterion("QF between", value1, value2, "qf");
            return (Criteria) this;
        }

        public Criteria andQfNotBetween(String value1, String value2) {
            addCriterion("QF not between", value1, value2, "qf");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andZtcIsNull() {
            addCriterion("ZTC is null");
            return (Criteria) this;
        }

        public Criteria andZtcIsNotNull() {
            addCriterion("ZTC is not null");
            return (Criteria) this;
        }

        public Criteria andZtcEqualTo(String value) {
            addCriterion("ZTC =", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcNotEqualTo(String value) {
            addCriterion("ZTC <>", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcGreaterThan(String value) {
            addCriterion("ZTC >", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcGreaterThanOrEqualTo(String value) {
            addCriterion("ZTC >=", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcLessThan(String value) {
            addCriterion("ZTC <", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcLessThanOrEqualTo(String value) {
            addCriterion("ZTC <=", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcLike(String value) {
            addCriterion("ZTC like", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcNotLike(String value) {
            addCriterion("ZTC not like", value, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcIn(List<String> values) {
            addCriterion("ZTC in", values, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcNotIn(List<String> values) {
            addCriterion("ZTC not in", values, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcBetween(String value1, String value2) {
            addCriterion("ZTC between", value1, value2, "ztc");
            return (Criteria) this;
        }

        public Criteria andZtcNotBetween(String value1, String value2) {
            addCriterion("ZTC not between", value1, value2, "ztc");
            return (Criteria) this;
        }

        public Criteria andTjmIsNull() {
            addCriterion("TJM is null");
            return (Criteria) this;
        }

        public Criteria andTjmIsNotNull() {
            addCriterion("TJM is not null");
            return (Criteria) this;
        }

        public Criteria andTjmEqualTo(String value) {
            addCriterion("TJM =", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmNotEqualTo(String value) {
            addCriterion("TJM <>", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmGreaterThan(String value) {
            addCriterion("TJM >", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmGreaterThanOrEqualTo(String value) {
            addCriterion("TJM >=", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmLessThan(String value) {
            addCriterion("TJM <", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmLessThanOrEqualTo(String value) {
            addCriterion("TJM <=", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmLike(String value) {
            addCriterion("TJM like", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmNotLike(String value) {
            addCriterion("TJM not like", value, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmIn(List<String> values) {
            addCriterion("TJM in", values, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmNotIn(List<String> values) {
            addCriterion("TJM not in", values, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmBetween(String value1, String value2) {
            addCriterion("TJM between", value1, value2, "tjm");
            return (Criteria) this;
        }

        public Criteria andTjmNotBetween(String value1, String value2) {
            addCriterion("TJM not between", value1, value2, "tjm");
            return (Criteria) this;
        }

        public Criteria andLwdwIsNull() {
            addCriterion("LWDW is null");
            return (Criteria) this;
        }

        public Criteria andLwdwIsNotNull() {
            addCriterion("LWDW is not null");
            return (Criteria) this;
        }

        public Criteria andLwdwEqualTo(String value) {
            addCriterion("LWDW =", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwNotEqualTo(String value) {
            addCriterion("LWDW <>", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwGreaterThan(String value) {
            addCriterion("LWDW >", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwGreaterThanOrEqualTo(String value) {
            addCriterion("LWDW >=", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwLessThan(String value) {
            addCriterion("LWDW <", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwLessThanOrEqualTo(String value) {
            addCriterion("LWDW <=", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwLike(String value) {
            addCriterion("LWDW like", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwNotLike(String value) {
            addCriterion("LWDW not like", value, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwIn(List<String> values) {
            addCriterion("LWDW in", values, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwNotIn(List<String> values) {
            addCriterion("LWDW not in", values, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwBetween(String value1, String value2) {
            addCriterion("LWDW between", value1, value2, "lwdw");
            return (Criteria) this;
        }

        public Criteria andLwdwNotBetween(String value1, String value2) {
            addCriterion("LWDW not between", value1, value2, "lwdw");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}