package deepthinking.dao.mapper;

import deepthinking.domain.TbYwScsjFile;
import deepthinking.domain.TbYwScsjFileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbYwScsjFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbYwScsjFileSqlProvider.class, method="countByExample")
    long countByExample(TbYwScsjFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TbYwScsjFileSqlProvider.class, method="deleteByExample")
    int deleteByExample(TbYwScsjFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @Insert({
        "insert into TB_YW_SCSJ_FILE (SCID, KM, ",
        "BM, YBS, ZT, ",
        "RKSJ, SCBT, SCDX, ",
        "SCLJ, SCGS, SCLB, ",
        "LRRY, LRSJ, BWXS, ",
        "MMDJ, FWSJ, CSSJ, ",
        "FWBH, QF, BZ, ",
        "ZTC, TJM, LWDW, ",
        "NR)",
        "values (#{scid,jdbcType=VARCHAR}, #{km,jdbcType=VARCHAR}, ",
        "#{bm,jdbcType=VARCHAR}, #{ybs,jdbcType=VARCHAR}, #{zt,jdbcType=VARCHAR}, ",
        "#{rksj,jdbcType=DATE}, #{scbt,jdbcType=VARCHAR}, #{scdx,jdbcType=INTEGER}, ",
        "#{sclj,jdbcType=VARCHAR}, #{scgs,jdbcType=VARCHAR}, #{sclb,jdbcType=VARCHAR}, ",
        "#{lrry,jdbcType=VARCHAR}, #{lrsj,jdbcType=DATE}, #{bwxs,jdbcType=VARCHAR}, ",
        "#{mmdj,jdbcType=VARCHAR}, #{fwsj,jdbcType=DATE}, #{cssj,jdbcType=DATE}, ",
        "#{fwbh,jdbcType=VARCHAR}, #{qf,jdbcType=VARCHAR}, #{bz,jdbcType=VARCHAR}, ",
        "#{ztc,jdbcType=VARCHAR}, #{tjm,jdbcType=VARCHAR}, #{lwdw,jdbcType=VARCHAR}, ",
        "#{nr,jdbcType=LONGVARBINARY})"
    })
    int insert(TbYwScsjFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @InsertProvider(type=TbYwScsjFileSqlProvider.class, method="insertSelective")
    int insertSelective(TbYwScsjFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbYwScsjFileSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="SCID", property="scid", jdbcType=JdbcType.VARCHAR),
        @Result(column="KM", property="km", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM", property="bm", jdbcType=JdbcType.VARCHAR),
        @Result(column="YBS", property="ybs", jdbcType=JdbcType.VARCHAR),
        @Result(column="ZT", property="zt", jdbcType=JdbcType.VARCHAR),
        @Result(column="RKSJ", property="rksj", jdbcType=JdbcType.DATE),
        @Result(column="SCBT", property="scbt", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCDX", property="scdx", jdbcType=JdbcType.INTEGER),
        @Result(column="SCLJ", property="sclj", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCGS", property="scgs", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCLB", property="sclb", jdbcType=JdbcType.VARCHAR),
        @Result(column="LRRY", property="lrry", jdbcType=JdbcType.VARCHAR),
        @Result(column="LRSJ", property="lrsj", jdbcType=JdbcType.DATE),
        @Result(column="BWXS", property="bwxs", jdbcType=JdbcType.VARCHAR),
        @Result(column="MMDJ", property="mmdj", jdbcType=JdbcType.VARCHAR),
        @Result(column="FWSJ", property="fwsj", jdbcType=JdbcType.DATE),
        @Result(column="CSSJ", property="cssj", jdbcType=JdbcType.DATE),
        @Result(column="FWBH", property="fwbh", jdbcType=JdbcType.VARCHAR),
        @Result(column="QF", property="qf", jdbcType=JdbcType.VARCHAR),
        @Result(column="BZ", property="bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="ZTC", property="ztc", jdbcType=JdbcType.VARCHAR),
        @Result(column="TJM", property="tjm", jdbcType=JdbcType.VARCHAR),
        @Result(column="LWDW", property="lwdw", jdbcType=JdbcType.VARCHAR),
        @Result(column="NR", property="nr", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<TbYwScsjFile> selectByExampleWithBLOBs(TbYwScsjFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbYwScsjFileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="SCID", property="scid", jdbcType=JdbcType.VARCHAR),
        @Result(column="KM", property="km", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM", property="bm", jdbcType=JdbcType.VARCHAR),
        @Result(column="YBS", property="ybs", jdbcType=JdbcType.VARCHAR),
        @Result(column="ZT", property="zt", jdbcType=JdbcType.VARCHAR),
        @Result(column="RKSJ", property="rksj", jdbcType=JdbcType.DATE),
        @Result(column="SCBT", property="scbt", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCDX", property="scdx", jdbcType=JdbcType.INTEGER),
        @Result(column="SCLJ", property="sclj", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCGS", property="scgs", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCLB", property="sclb", jdbcType=JdbcType.VARCHAR),
        @Result(column="LRRY", property="lrry", jdbcType=JdbcType.VARCHAR),
        @Result(column="LRSJ", property="lrsj", jdbcType=JdbcType.DATE),
        @Result(column="BWXS", property="bwxs", jdbcType=JdbcType.VARCHAR),
        @Result(column="MMDJ", property="mmdj", jdbcType=JdbcType.VARCHAR),
        @Result(column="FWSJ", property="fwsj", jdbcType=JdbcType.DATE),
        @Result(column="CSSJ", property="cssj", jdbcType=JdbcType.DATE),
        @Result(column="FWBH", property="fwbh", jdbcType=JdbcType.VARCHAR),
        @Result(column="QF", property="qf", jdbcType=JdbcType.VARCHAR),
        @Result(column="BZ", property="bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="ZTC", property="ztc", jdbcType=JdbcType.VARCHAR),
        @Result(column="TJM", property="tjm", jdbcType=JdbcType.VARCHAR),
        @Result(column="LWDW", property="lwdw", jdbcType=JdbcType.VARCHAR)
    })
    List<TbYwScsjFile> selectByExample(TbYwScsjFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbYwScsjFileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TbYwScsjFile record, @Param("example") TbYwScsjFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbYwScsjFileSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") TbYwScsjFile record, @Param("example") TbYwScsjFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YW_SCSJ_FILE
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbYwScsjFileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TbYwScsjFile record, @Param("example") TbYwScsjFileCriteria example);
}